title: Long Haul
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: https://alvaradocde.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5
future: true
safe: false

# All Jekyll-Bootstrap specific configurations are namespaced into this hash
#
JB :
  version : 0.2.13


navigation:
 - title: Home
   url: /index.html
 - title: About me
   url: /about
 - title: Contact
   url: /contact

social:
   github: alvaradocde
   twitter: alvaradocde
   facebook: alvaradocde291
   email: alvaradocde@gmail.com

google_analytics: "UA-58263416-1"
